Repository godot-sdk-integrations/godot-meta-toolkit, pull requests merged in 2025-02, with the labels that each got.

#7 Fix some SDK code gen issues
  generate_platform_sdk_bindings.py
  toolkit/src/main/cpp/include/util.h
  toolkit/src/main/cpp/platform_sdk/meta_platform_sdk.cpp
Labels: bug

#6 Add more documentation
  doc_classes/MetaPlatformSDK.xml
  doc_classes/MetaPlatformSDK_AchievementDefinition.xml
  doc_classes/MetaPlatformSDK_AdvancedAbuseReportOptions.xml
  doc_classes/MetaPlatformSDK_AssetFileDownloadUpdate.xml
  doc_classes/MetaPlatformSDK_ChallengeEntry.xml
  doc_classes/MetaPlatformSDK_ChallengeOptions.xml
  doc_classes/MetaPlatformSDK_HttpTransferUpdate.xml
  doc_classes/MetaPlatformSDK_InviteOptions.xml
  doc_classes/MetaPlatformSDK_LeaderboardEntry.xml
  doc_classes/MetaPlatformSDK_LeaderboardUpdateStatus.xml
  doc_classes/MetaPlatformSDK_Purchase.xml
  doc_classes/MetaPlatformSDK_RosterOptions.xml
  doc_classes/MetaPlatformSDK_UserReportID.xml
  docs/manual/platform_sdk/getting_started.rst
Labels: documentation

#8 Remove `*_long()` suffix from function names
  doc_classes/MetaPlatformSDK_AssetFileDownloadUpdate.xml
  generate_platform_sdk_bindings.py
Labels: bug

#9 Document `MetaPlatformSDK_Message.error` rather than `get_error()`
  doc_classes/MetaPlatformSDK_Error.xml
  doc_classes/MetaPlatformSDK_Message.xml
Labels: documentation

#10 Update `CHANGES.md` for the 1.0.1 release
  CHANGES.md
Labels: documentation

#11 Include API documentation in the editor
  .gitignore
  SConstruct
Labels: bug

#13 Update for v72 of the Platform SDK
  .gitignore
  doc_classes/MetaPlatformSDK.xml
  doc_classes/MetaPlatformSDK_BillingPlan.xml
  doc_classes/MetaPlatformSDK_BillingPlanArray.xml
  doc_classes/MetaPlatformSDK_ContentRating.xml
  doc_classes/MetaPlatformSDK_PaidOffer.xml
  doc_classes/MetaPlatformSDK_Product.xml
  doc_classes/MetaPlatformSDK_Purchase.xml
  doc_classes/MetaPlatformSDK_TrialOffer.xml
  doc_classes/MetaPlatformSDK_TrialOfferArray.xml
  scripts/update_doc_classes_xml.sh
Labels: enhancement

#14 Update `CHANGES.md` for the 1.0.2 release
  CHANGES.md
Labels: enhancement
